<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/compute/v1/instance_service.proto

namespace App\Rest\Hetzner\Instance;
use Illuminate\Support\Facades\Http;

class ListInstances 
{
	private $api_key;
	public function __construct($api_key=null) {
		$this->api_key=$api_key;

    }

	public function execute($retry=3)
	{	

	sleep(1);
		if($retry<0)return array();
		if($retry<3)sleep(3-$retry);
		$result=array();
		
		
		for($i=0;;$i++)
		{
			sleep(3-$retry);
			$response = Http::withToken($this->api_key)->get("https://api.hetzner.cloud/v1/servers/?page=".$i."&per_page=50");
			
			$data=$response->json();
			if(!isset($data['meta']['pagination']))return $this->execute($retry-1);
			if($data['meta']['pagination']['last_page']<$i)return $this->execute($retry-1);
			foreach($data['servers'] as $server)
			{
			array_push($result,
							array(
					'name'=>$server['name'],
					'id'=>$server['id'],
					'ip'=>$server['public_net']['ipv4']['ip'],
					'status'=>$server['status']	
								
								)
								
						);
			}
			
		}
			
		return $result;

		}
}

