<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/compute/v1/instance_service.proto

namespace App\Rest\Yandex\Instance;


use GuzzleHttp\Client;
use GuzzleHttp\Exception\RequestException;
use App\Models\IamToken;

class ListInstances 
{
	private $folderId;
	private $IamToken;

	private $url="https://compute.api.cloud.yandex.net/compute/v1/instances";
	public function __construct($folderId=null) {
		$this->folderId=$folderId;
		$iamtoken = IamToken::find(1);
		$this->IamToken=$iamtoken->token;

    }

	public function execute($retry=3)
	{
		sleep(1);
		if($retry<0)return array();
		if($retry<3)sleep(3-$retry);
		
		
			try
			{
				$client = new Client([
				'base_uri' => $this->url,
				'timeout'  => 10.0,
				'headers' => ['Authorization' => 'Bearer '.$this->IamToken],
				'query' => ['folderId' => $this->folderId]
				]);

				$response=$client->request('GET');
				$body=json_decode($response->getBody());
				if(!isset($body->{'instances'}))return array();
				return $body->{'instances'};
				
				
				
			}
				catch (RequestException $e) {

					if ($e->hasResponse()) {

					}
					return $this->execute($retry-1);
				}
	


		}
}

