// block registry — reusable functional Lego blocks; pages are composed from these by name.
import HeroBlock from './HeroBlock.vue'
import StatsBlock from './StatsBlock.vue'
import NewsletterBlock from './NewsletterBlock.vue'
import ContactBlock from './ContactBlock.vue'
import FooterBlock from './FooterBlock.vue'
import SearchBlock from './SearchBlock.vue'
import ProductGridBlock from './ProductGridBlock.vue'
import FeedBlock from './FeedBlock.vue'
import CommentsBlock from './CommentsBlock.vue'
import DetailBlock from './DetailBlock.vue'
import CartBlock from './CartBlock.vue'
import AuthBlock from './AuthBlock.vue'
import ResetBlock from './ResetBlock.vue'
import ProfileBlock from './ProfileBlock.vue'
import LookupBlock from './LookupBlock.vue'
import JobBlock from './JobBlock.vue'
import FileBlock from './FileBlock.vue'
import UploadBlock from './UploadBlock.vue'
import WebhookBlock from './WebhookBlock.vue'
import DocsBlock from './DocsBlock.vue'
import RenderBlock from './RenderBlock.vue'
import BackupBlock from './BackupBlock.vue'
import ImportBlock from './ImportBlock.vue'
export const BLOCKS = { hero: HeroBlock, stats: StatsBlock, newsletter: NewsletterBlock, contact: ContactBlock, footer: FooterBlock, search: SearchBlock, productgrid: ProductGridBlock, feed: FeedBlock, comments: CommentsBlock, detail: DetailBlock, cart: CartBlock, auth: AuthBlock, reset: ResetBlock, profile: ProfileBlock, lookup: LookupBlock, job: JobBlock, file: FileBlock, upload: UploadBlock, webhook: WebhookBlock, docs: DocsBlock, render: RenderBlock, backup: BackupBlock, import: ImportBlock }
