const express = require('express')
const cors = require('cors')
const path = require('path')
require('./db')
const app = express()
app.disable('x-powered-by')
app.use(cors())
app.use(express.json({ limit: '1mb' }))
app.get('/api/version', (req, res) => res.json({ name: 'HelpDeskAI', product: 'AI Support Desk', version: '1.4.0', model: 'acme-assist-mini', node: process.version }))
app.get('/healthz', (req, res) => res.json({ ok: true }))
app.use('/api', require('./routes'))
app.use('/api', (req, res) => res.status(404).json({ error: 'not found' }))
app.use(express.static(path.join(__dirname, 'public')))
app.get('*', (req, res) => res.sendFile(path.join(__dirname, 'public', 'index.html')))
app.use((err, req, res, next) => res.status(500).json({ error: err.message }))
app.listen(80, () => console.log('HelpDeskAI on :80'))
