<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/compute/v1/instance_service.proto

namespace App\Rest\Google\Instance;


use GuzzleHttp\Client;
use GuzzleHttp\Exception\RequestException;
use Google\Cloud\Compute\V1\InstancesClient;
use Google\Cloud\Compute\V1\AttachedDisk;
use Google\Cloud\Compute\V1\AttachedDiskInitializeParams;
use Google\Cloud\Compute\V1\Instance;
use Google\Cloud\Compute\V1\NetworkInterface;
use Google\Cloud\Compute\V1\Operation;
use Google\Cloud\Compute\V1\ZoneOperationsClient;
use Google\Cloud\Compute\V1\AccessConfig;
use Google\Cloud\Compute\V1\Scheduling;
use Google\ApiCore\ApiException;

class DeleteInstance 
{
	private $projectId;
	private $keypath;
	private $name;
	private $zone;
	public function __construct($name=null,$projectId=null,$keypath=null) {
		$this->projectId=$projectId;
		$this->keypath=$keypath;
		$this->name=$name;
		$this->zone="europe-west1-b";
    }

	public function execute($retry=3)
	{

		sleep(1);
		if($retry<0)return TRUE;
		if($retry<3)sleep(3-$retry);
		putenv('GOOGLE_APPLICATION_CREDENTIALS='.$this->keypath);
		try
		{
			$instancesClient = new InstancesClient();
			$instancesClient->delete($this->name, $this->projectId, $this->zone);
		}
		catch(ApiException $e)
		{
			return $this->execute($retry-1);
		}
		return TRUE;

	}
}

